apiVersion: apps/v1
kind: Deployment
metadata:
  name: gonewest
spec:
  replicas: 3
  selector:
    matchLabels:
      name: gonewest
  template:
    metadata:
      labels:
        name: gonewest
    spec:
      containers:
      - image: kiranbabycontainerreg.azurecr.io/kiranbabycontainerrepo:gonewest
        name: kiranbabycontainerreg
        ports:
          - containerPort: 8081
      imagePullSecrets: 
      - name: gonewestsecret
status: {}
---
apiVersion: v1
kind: Service
metadata:
  name: gonewest+service
spec:
  type: LoadBalancer
  selector:
    name: gonewest
  ports:
  - name: http  
    port: 80
    targetPort: 8081
